version: "3"

######### Services ###################################

services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      - 8001:8001
      - 5173:5173
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/src/
    working_dir: /var/www/src/

  node:
    build:
      context: docker/node
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/src/
    working_dir: /var/www/src/
    command: >
      sh -c "yarn && yarn dev --host 0.0.0.0"
    tty: true
